home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.kegiatan, name='kegiatan'),
    path('delete/<str:pk>', views.delete, name='kegiatanDelete'),
    path('delete/anggota/<str:pk>', views.deleteAnggota, name='anggotaDelete'),
]

story_6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.

class Kegiatan(models.Model):
    kegiatan = models.CharField(max_length=100)
    def __str__(self):
        return self.kegiatan

class Anggota(models.Model):
    anggota = models.CharField(max_length=100)
    aktivitas = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)
    def __str__(self):
        return self.anggota

    

home/forms.py
from django import forms
from .models import Kegiatan, Anggota

class FormKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'
        widgets = {
            'kegiatan' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Apa yang ingin anda lakukan?"
            }),
        }

class FormAnggota(forms.ModelForm):
    class Meta:
        model = Anggota
        fields = '__all__' 
        widgets = {
            'anggota' : forms.TextInput(attrs= {
                'class': 'form-control',
                'placeholder': "Ingin bergabung?"
            }),
        }

home/views.py
from django.shortcuts import render, redirect
from .models import Anggota, Kegiatan
from .forms import FormAnggota, FormKegiatan
from django.contrib import messages


# Create your views here.

def kegiatan(request):
    if request.method == "POST":
        formA = FormKegiatan(request.POST)
        formB = FormAnggota(request.POST)
        
        if formA.is_valid():
            formA.save()
            messages.success(request, (f"Kegiatan {request.POST['kegiatan']} berhasil ditambahkan!"))
            return redirect('home:kegiatan')

        elif formB.is_valid():
            formB.save()
            messages.success(request, (f"{request.POST['anggota']} berhasil bergabung!"))
            return redirect('home:kegiatan')

        else :
            messages.warning(request, (f"Input tidak sesuai!"))
            return redirect('home:kegiatan')
    
    else:
        formA = FormKegiatan()
        formB = FormAnggota()
        listKegiatan = Kegiatan.objects.all()
        listAnggota = Anggota.objects.all()
        context = {
            'formA' : formA,
            'formB' : formB,
            'listKegiatan' : listKegiatan,
            'listAnggota' : listAnggota,
        }
        return render(request,'home/index.html', context)

def delete(request,pk):
    kegiatan = Kegiatan.objects.get(id=pk)
    kegiatan.delete()
    messages.warning(request, (f"Kegiatan {kegiatan} berhasil dihapus!"))
    return redirect('home:kegiatan')

def deleteAnggota(request,pk):
    anggota = Anggota.objects.get(id=pk)
    anggota.delete()
    messages.warning(request, (f"{anggota} berhasil dihapus"))
    return redirect('home:kegiatan')

home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Daftar Kegiatan</title>
</head>
<body>
    {% block content%}
    
    {% endblock content%}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% block content %}
<div class="container py-4">
    <h1 class="display-4 text-center pb-4 border-bottom">Aktivitas Ku</h1>
    <Form method="POST" class="row my-5">
        {% csrf_token %}
        <div class="col-7 ml-auto">
            {{ formA.kegiatan }}
        </div>
        <button type="submit" class="btn btn-dark col-2 mr-auto">Tambah Kegiatan</button>
    </Form>
    <hr>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="d-flex justify-content-around flex-wrap pb-4">
        {% for kegiatan in listKegiatan %}
        <div class="card bg-light mt-5" style="width: 18rem;">
            <div class="card-header">
                <div class="row">
                    <h5 class="col-10 mb-2">{{ kegiatan }}</h5>
                    <a href="{% url 'home:kegiatanDelete' kegiatan.id %}" class="col-2">
                        <button type="button" class="close mb-2">&times;</button>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <h6 class="card-title">Anggota:</h6>
                <p></p>
                <ul>

                    {% for anggota in listAnggota %}
                    {% if anggota.aktivitas.id == kegiatan.id %}
                    <li class="row">
                        <h5 class="col-10">{{ anggota }}</h5>
                        <a href="{% url 'home:anggotaDelete' anggota.id %}" class="col-2">
                            <button type="button" class="close">&times;</button>
                        </a>    
                    </li>
                    {% endif %}
                    {% endfor %}

                </ul>
                <form method="POST">
                    {% csrf_token %}
                    {{ formB.anggota }}
                    <input name="aktivitas" type="text" value="{{ kegiatan.id }}" style="display: none;">
                    <button type="submit" class="btn btn-dark col-6 mt-2">Gabung</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}